{
 "title": "LUKSO Lighthouse Dashboard EUR",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Network Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Total Validator Balance (LYX)",
   "type": "stat",
   "description": "Sum of all validator balances.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_balance_gwei{job=\"validator-client-job\"}) / 1e9",
     "legendFormat": "vbal"
    }
   ]
  },
  {
   "title": "Total Earnings (LYX)",
   "type": "stat",
   "description": "Total LYX return on the initial effective stake of active local validators.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_balance_gwei{job=\"validator-client-job\"}) / 1e9 - (32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"}))"
    }
   ]
  },
  {
   "title": "Total Return",
   "type": "stat",
   "description": "Total percentage return on the initial effective stake of active local validators. Excess deposits will be reflected as earnings.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(validator_monitor_balance_gwei{job=\"validator-client-job\"}) / 1e9 - (32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"}))) / (32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"}))"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "description": "Number of beacon nodes to which this node is connected.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",job=\"consensus-client-job\"}"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "stat",
   "description": "The percentage of LYX balances expected to attest that are actually attesting.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"consensus-client-job\"} / beacon_prev_epoch_active_gwei{job=\"consensus-client-job\"} )"
    }
   ]
  },
  {
   "title": "Network Liveness",
   "type": "stat",
   "description": "A metric expressing the distance between the current finalized epoch and the expected finalized epoch based on the genesis time. 100% means the expected and current finalized epochs are the same. The metric reaches 0% when the finalized epoch is 25 epochs behind the expected epoch.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1-(4*((floor(slotclock_present_slot{job=\"consensus-client-job\"}/32) - beacon_finalized_epoch{job=\"consensus-client-job\"} - 2)/100))),0)"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "description": "The percentage of LYX balances expected to attest that are actually attesting.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Participation Rate" }
   ],
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"consensus-client-job\"} / beacon_prev_epoch_active_gwei{job=\"consensus-client-job\"} )",
     "legendFormat": "participation rate"
    }
   ]
  },
  {
   "title": "Total Validator Balance (EUR)",
   "type": "stat",
   "description": "Sum of all validator balances multiplied by the price of LYX in EUR.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lyxeur", "legendFormat": "lyxeur" },
    {
     "expr": "sum(validator_monitor_balance_gwei{job=\"validator-client-job\"}) / 1e9",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Total Earnings (EUR)",
   "type": "stat",
   "description": "Total earnings in EUR.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_balance_gwei{job=\"validator-client-job\"}) / 1e9 - (32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"}))",
     "legendFormat": "total_balance"
    },
    { "expr": "lyxeur", "legendFormat": "lyxeur" }
   ]
  },
  {
   "title": "LYX Price (EUR)",
   "type": "stat",
   "description": "Price of LYX in EUR.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lyxeur", "legendFormat": "lyxeur" }
   ]
  },
  {
   "title": "Max. Inactivity Score",
   "type": "stat",
   "description": "Current maximum inactvity score across all validators.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(validator_monitor_inactivity_score{job=\"validator-client-job\"})"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "stat",
   "description": "Current, justified, and finalized epochs. In this order, these three values should be sequentially decreasing.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(slotclock_present_slot{job=\"consensus-client-job\"} / 32)",
     "legendFormat": "current"
    },
    {
     "expr": "beacon_current_justified_epoch{job=\"consensus-client-job\"}",
     "legendFormat": "justified"
    },
    {
     "expr": "beacon_finalized_epoch {job=\"consensus-client-job\"} ",
     "legendFormat": "finalized"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "description": "Current slot and head slot",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "slotclock_present_slot{job=\"consensus-client-job\"}",
     "legendFormat": "current slot"
    },
    {
     "expr": "beacon_head_slot{job=\"consensus-client-job\"}",
     "legendFormat": "head slot"
    }
   ]
  },
  {
   "title": "Local Validators",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Network Validators",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Hourly Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_monitor_balance_gwei{job=\"validator-client-job\"}) - sum(validator_monitor_balance_gwei{job=\"validator-client-job\"} offset 1h != 0)) / 1e9) - (32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"})) + (32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"} offset 1h))"
    }
   ]
  },
  {
   "title": "Daily Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last day",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_monitor_balance_gwei{job=\"validator-client-job\"}) - sum(validator_monitor_balance_gwei{job=\"validator-client-job\"} offset 1d != 0)) / 1e9) - (32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"})) + (32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"} offset 1d))"
    }
   ]
  },
  {
   "title": "Weekly Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last week",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_monitor_balance_gwei{job=\"validator-client-job\"}) - sum(validator_monitor_balance_gwei{job=\"validator-client-job\"} offset 7d != 0)) / 1e9) - (32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"})) + (32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"} offset 7d))"
    }
   ]
  },
  {
   "title": "Monthly Earnings",
   "type": "stat",
   "description": "Increase in all local validator balances over the last month",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(validator_monitor_balance_gwei{job=\"validator-client-job\"}) - sum(validator_monitor_balance_gwei{job=\"validator-client-job\"} offset 30d != 0)) / 1e9) - (32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"})) + (32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"} offset 30d))"
    }
   ]
  },
  {
   "title": "Validator Counts",
   "type": "stat",
   "description": "Counts of active, slashed and exited validators.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_head_state_active_validators_total{job=\"consensus-client-job\"}",
     "legendFormat": "active"
    },
    {
     "expr": "beacon_head_state_slashed_validators_total{job=\"consensus-client-job\"}",
     "legendFormat": "slashed"
    },
    {
     "expr": "beacon_head_state_exited_validators_total{job=\"consensus-client-job\"}",
     "legendFormat": "exited"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "description": "Number of pending and existing validators over time. Pending validators are shown as positive values, while exiting validators are shown as negative values.",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "validators" }
   ],
   "targets": [
    {
     "expr": "beacon_head_state_pending_validators_total{job=\"consensus-client-job\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "beacon_head_state_exiting_validators_total{job=\"consensus-client-job\"}",
     "legendFormat": "exiting"
    },
    {
     "expr": "beacon_head_state_active_validators_total{job=\"consensus-client-job\"}",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Validator Queues",
   "type": "stat",
   "description": "Current number of pending and exiting validators",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_head_state_pending_validators_total{job=\"consensus-client-job\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "beacon_head_state_exiting_validators_total{job=\"consensus-client-job\"}",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Hourly Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((sum(validator_monitor_balance_gwei{job=\"validator-client-job\"}) - sum(validator_monitor_balance_gwei{job=\"validator-client-job\"} offset 1h != 0)) / 1e9) - 32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"}) + 32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"} offset 1h)) / (32 * avg_over_time(count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"})[1h:])) * 365 * 24",
     "legendFormat": "annualized hourly return"
    }
   ]
  },
  {
   "title": "Daily Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last day",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((sum(validator_monitor_balance_gwei{job=\"validator-client-job\"}) - sum(validator_monitor_balance_gwei{job=\"validator-client-job\"} offset 1d != 0)) / 1e9) - 32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"}) + 32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"} offset 1d)) / (32 * avg_over_time(count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"})[1d:])) * 365",
     "legendFormat": "annualized daily return"
    }
   ]
  },
  {
   "title": "Weekly Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last week",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((sum(validator_monitor_balance_gwei{job=\"validator-client-job\"}) - sum(validator_monitor_balance_gwei{job=\"validator-client-job\"} offset 7d != 0)) / 1e9) - 32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"}) + 32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"} offset 7d)) / (32 * avg_over_time(count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"})[7d:])) * (365/7)",
     "legendFormat": "annualized weekly return"
    }
   ]
  },
  {
   "title": "Monthly Return, Annualized",
   "type": "stat",
   "description": "Percentage increase in all local validator balances over the last month",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((sum(validator_monitor_balance_gwei{job=\"validator-client-job\"}) - sum(validator_monitor_balance_gwei{job=\"validator-client-job\"} offset 30d != 0)) / 1e9) - 32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"}) + 32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"} offset 30d)) / (32 * avg_over_time(count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"})[30d:])) * (365/30)",
     "legendFormat": "annualized monthly return"
    }
   ]
  },
  {
   "title": "Avg. Balance",
   "type": "stat",
   "description": "Average validator balance across the network",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "beacon_head_state_total_active_balance_gwei{job=\"consensus-client-job\"} / beacon_head_state_active_validators_total{job=\"consensus-client-job\"} / 1e9",
     "legendFormat": "lyx"
    }
   ]
  },
  {
   "title": "Queue Lengths",
   "type": "stat",
   "description": "Estimated length of time until all pending and exiting validators have cleared the queues.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((beacon_head_state_pending_validators_total{job=\"consensus-client-job\"} / 4) * 6.4)",
     "legendFormat": "pending"
    },
    {
     "expr": "((beacon_head_state_exiting_validators_total{job=\"consensus-client-job\"} / 4) * 6.4)",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Validator Process Stats",
   "type": "table-old",
   "description": "validator stats by public key over the lifetime of the validator process ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_monitor_status{job=\"validator-client-job\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_monitor_balance_gwei{job=\"validator-client-job\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") / 1e9",
     "legendFormat": "balance"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_monitor_successful_proposals_total{job=\"validator-client-job\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_monitor_successful_attestations_total{job=\"validator-client-job\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_monitor_successful_aggregations_total{job=\"validator-client-job\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_monitor_failed_attestations_total{job=\"validator-client-job\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_monitor_failed_aggregations_total{job=\"validator-client-job\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_monitor_inactivity_score{job=\"validator-client-job\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    }
   ]
  },
  {
   "title": "Client Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "The number of peers to which the beacon chain is connected",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",job=\"consensus-client-job\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Process Uptimes",
   "type": "stat",
   "description": "The length of time the beacon chain and validator processes have been running.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"consensus-client-job\"})/3600",
     "legendFormat": "beacon chain"
    },
    {
     "expr": "(time()-process_start_time_seconds{job=\"validator-client-job\"})/3600",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "Beacon Logs",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{job=\"consensus-client-job\", level=\"error\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{job=\"consensus-client-job\", level=\"warning\"}[$__range]))*3600",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Lighthouse Versions",
   "type": "table",
   "description": "Versions of the currently running Lighthouse clients.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "max(lighthouse_info{job=\"consensus-client-job\"}) by (job, version)"
    }
   ]
  },
  {
   "title": "Validator Logs",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{job=\"validator-client-job\", level=\"error\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{job=\"validator-client-job\", level=\"warning\"}[$__range]))*3600",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Server",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Client Memory Usage",
   "type": "graph",
   "description": "Beacon chain and validator memory usage on the server.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"consensus-client-job\"}",
     "legendFormat": "beacon memory"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"validator-client-job\"}",
     "legendFormat": "validator memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Processor usage on the server",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"system\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"user\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"nice\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"iowait\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"steal\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"idle\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"irq\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"softirq\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"guest\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "Network transmission (tx) and reception (rx) rates",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node-exporter-job\",device='enp1s0'}[5m])*8 or irate(node_network_transmit_bytes{job=\"node-exporter-job\",device='enp1s0'}[5m])*8 or irate(node_network_transmit_bytes_total{job=\"node-exporter-job\",device='eno1'}[5m])*8 or irate(node_network_transmit_bytes{job=\"node-exporter-job\",device='eno1'}[5m])*8",
     "legendFormat": "tx"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node-exporter-job\",device='enp1s0'}[5m])*8 or irate(node_network_receive_bytes{job=\"node-exporter-job\",device='enp1s0'}[5m])*8 or irate(node_network_receive_bytes_total{job=\"node-exporter-job\",device='eno1'}[5m])*8 or irate(node_network_receive_bytes{job=\"node-exporter-job\",device='eno1'}[5m])*8",
     "legendFormat": "rx"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job=\"node-exporter-job\"})-sum(node_filesystem_avail_bytes{job=\"node-exporter-job\"}))/sum(node_filesystem_size_bytes{job=\"node-exporter-job\"})",
     "legendFormat": "disk usage"
    }
   ]
  },
  {
   "title": "Server Memory Usage",
   "type": "graph",
   "description": "Memory usage on the server",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{job=\"node-exporter-job\"} - node_memory_MemFree_bytes{job=\"node-exporter-job\"} - node_memory_Buffers_bytes{job=\"node-exporter-job\"} - node_memory_Cached_bytes{job=\"node-exporter-job\"} - node_memory_SwapCached_bytes{job=\"node-exporter-job\"} - node_memory_Slab_bytes{job=\"node-exporter-job\"} - node_memory_PageTables_bytes{job=\"node-exporter-job\"} - node_memory_VmallocUsed_bytes{job=\"node-exporter-job\"} ) or ( node_memory_MemTotal{job=\"node-exporter-job\"} - node_memory_MemFree{job=\"node-exporter-job\"} - node_memory_Buffers{job=\"node-exporter-job\"} - node_memory_Cached{job=\"node-exporter-job\"} - node_memory_SwapCached{job=\"node-exporter-job\"} - node_memory_Slab{job=\"node-exporter-job\"} - node_memory_PageTables{job=\"node-exporter-job\"} - node_memory_VmallocUsed{job=\"node-exporter-job\"} )",
     "legendFormat": "apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter-job\"} or node_memory_Buffers{job=\"node-exporter-job\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter-job\"} or node_memory_Cached{job=\"node-exporter-job\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter-job\"} or node_memory_MemFree{job=\"node-exporter-job\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_Slab_bytes{job=\"node-exporter-job\"} or node_memory_Slab{job=\"node-exporter-job\"}",
     "legendFormat": "slab"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_coretemp_0\",job=\"node-exporter-job\",sensor=\"temp1\"}",
     "legendFormat": "cpu temp"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"google-ping-job\"}",
     "legendFormat": "google"
    },
    {
     "expr": "probe_duration_seconds{job=\"cloudflare-ping-job\"}",
     "legendFormat": "cloudflare"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Consensus Process Down",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"consensus-client-job\"}",
     "legendFormat": "beacon node"
    }
   ]
  },
  {
   "title": "Less than 2GB Free Memory",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes{job=\"node-exporter-job\"} or node_memory_MemFree{job=\"node-exporter-job\"}) + (node_memory_Cached_bytes{job=\"node-exporter-job\"} or node_memory_Cached{job=\"node-exporter-job\"})"
    }
   ]
  },
  {
   "title": "Validator Process Down",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"validator-client-job\"}",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "CPU Usage above 40%",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"user\",job=\"node-exporter-job\"}[5m]))"
    }
   ]
  },
  {
   "title": "Consensus Process Restarted",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"consensus-client-job\"})/3600",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk Usage above 60%",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job=\"node-exporter-job\"})-sum(node_filesystem_avail_bytes{job=\"node-exporter-job\"}))/sum(node_filesystem_size_bytes{job=\"node-exporter-job\"})"
    }
   ]
  },
  {
   "title": "Validator Process Restarted",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"validator-client-job\"})/3600"
    }
   ]
  },
  {
   "title": "CPU Temperature above 85 °C",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_coretemp_0\",job=\"node-exporter-job\",sensor=\"temp1\"}"
    }
   ]
  },
  {
   "title": "Below 40 Peers",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",job=\"consensus-client-job\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Google Ping above 10ms",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"google-ping-job\"}"
    }
   ]
  },
  {
   "title": "Participation Rate below 80%",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"consensus-client-job\"} / beacon_prev_epoch_active_gwei{job=\"consensus-client-job\"}) *100"
    }
   ]
  },
  {
   "title": "50 Slots Behind",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_slot{job=\"consensus-client-job\"} - beacon_head_slot{job=\"consensus-client-job\"}",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "No Hourly Earnings",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((sum(validator_monitor_balance_gwei{job=\"validator-client-job\"}) - sum(validator_monitor_balance_gwei{job=\"validator-client-job\"} offset 1h != 0)) / 1e9) - (32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"})) + (32 * count(validator_monitor_status{job=\"validator-client-job\",status=\"active_ongoing\"} offset 1h))",
     "legendFormat": "validators earning on 1h"
    }
   ]
  }
 ]
}