{
 "title": "LUKSO Teku Dashboard USD",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Network Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Local Validators",
   "type": "stat",
   "description": "Number of local Validators.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_local_validator_count{job=\"validator-client-job\"})"
    }
   ]
  },
  {
   "title": "Total Validator Balance (LYX)",
   "type": "stat",
   "description": "Sum of all validator balances.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "LYX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_local_validator_count{job=\"validator-client-job\"})*32",
     "legendFormat": "vbal"
    }
   ]
  },
  {
   "title": "LYX Price (USD)",
   "type": "stat",
   "description": "Price of LYX in USD.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lyxusd", "legendFormat": "lyxusd" }
   ]
  },
  {
   "title": "Total Validator Balance (USD)",
   "type": "stat",
   "description": "Sum of all validator balances multiplied by the price of LYX in USD.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lyxusd", "legendFormat": "lyxusd" },
    {
     "expr": "sum(validator_local_validator_count{job=\"validator-client-job\"})*32",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "stat",
   "description": "The percentage of LYX balances expected to attest that are actually attesting.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(beacon_previous_live_validators{job=\"consensus-client-job\"} / beacon_previous_active_validators{job=\"consensus-client-job\"})"
    }
   ]
  },
  {
   "title": "Network Liveness",
   "type": "stat",
   "description": "A metric expressing the distance between the current finalized epoch and the expected finalized epoch based on the genesis time. 100% means the expected and current finalized epochs are the same. The metric reaches 0% when the finalized epoch is 25 epochs behind the expected epoch.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1-(4*((floor(beacon_clock_time_slot{job=\"consensus-client-job\"}/32) - beacon_finalized_epoch{job=\"consensus-client-job\"} - 2)/100))),0)"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "description": "The percentage of LYX balances expected to attest that are actually attesting.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Participation Rate" }
   ],
   "targets": [
    {
     "expr": "(beacon_previous_live_validators{job=\"consensus-client-job\"} / beacon_previous_active_validators{job=\"consensus-client-job\"})",
     "legendFormat": "participation rate"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "description": "Number of beacon nodes to which this node is connected.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "libp2p_peers{job=\"consensus-client-job\"}"
    }
   ]
  },
  {
   "title": "Published Blocks",
   "type": "stat",
   "description": "Number of published blocks.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_beacon_node_requests_total{job=\"validator-client-job\",method=\"publish_block\",outcome=\"success\"})"
    }
   ]
  },
  {
   "title": "Published Attestations",
   "type": "stat",
   "description": "Number of published attestations.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_beacon_node_requests_total{job=\"validator-client-job\",method=\"publish_attestation\",outcome=\"success\"})"
    }
   ]
  },
  {
   "title": "Published Aggregates",
   "type": "stat",
   "description": "Number of published aggregates.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_beacon_node_requests_total{job=\"validator-client-job\",method=\"publish_aggregate_and_proofs\",outcome=\"success\"})"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "stat",
   "description": "Current, justified, and finalized epochs. In this order, these three values should be sequentially decreasing.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(beacon_clock_time_slot{job=\"consensus-client-job\"} / 32)",
     "legendFormat": "current"
    },
    {
     "expr": "beacon_current_justified_epoch{job=\"consensus-client-job\"}",
     "legendFormat": "justified"
    },
    {
     "expr": "beacon_finalized_epoch {job=\"consensus-client-job\"} ",
     "legendFormat": "finalized"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "description": "Current slot and head slot",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_slot{job=\"consensus-client-job\"}",
     "legendFormat": "current slot"
    },
    {
     "expr": "beacon_head_slot{job=\"consensus-client-job\"}",
     "legendFormat": "head slot"
    }
   ]
  },
  {
   "title": "Local Validators",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Network Validators",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Attestation Performance",
   "type": "graph",
   "description": "Percentage of attestations in each epoch with the correct head root, correct target root and that were successfully included in blocks.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "validator_performance_included_attestations{job=\"validator-client-job\"} / validator_performance_expected_attestations{job=\"validator-client-job\"}",
     "legendFormat": "Included Attestation"
    },
    {
     "expr": "validator_performance_correct_head_block_count{job=\"validator-client-job\"} / validator_performance_included_attestations{job=\"validator-client-job\"}",
     "legendFormat": "Correct Head"
    },
    {
     "expr": "validator_performance_correct_target_count{job=\"validator-client-job\"} / validator_performance_included_attestations{job=\"validator-client-job\"}",
     "legendFormat": "Correct Target"
    },
    {
     "expr": "\n(\nvalidator_performance_correct_head_block_count{job=\"validator-client-job\"} - (validator_performance_expected_attestations{job=\"validator-client-job\"} - validator_performance_correct_head_block_count{job=\"validator-client-job\"}) +\nvalidator_performance_correct_target_count{job=\"validator-client-job\"} - (validator_performance_expected_attestations{job=\"validator-client-job\"} - validator_performance_correct_target_count{job=\"validator-client-job\"}) +\nvalidator_performance_included_attestations{job=\"validator-client-job\"} - (validator_performance_expected_attestations{job=\"validator-client-job\"} - validator_performance_included_attestations{job=\"validator-client-job\"}) +\n(0.875  * validator_performance_included_attestations{job=\"validator-client-job\"} / validator_performance_inclusion_distance_average{job=\"validator-client-job\"})\n) / validator_performance_expected_attestations{job=\"validator-client-job\"} / 3.875",
     "legendFormat": "Attestation Rewards Earned"
    },
    {
     "expr": "validator_performance_included_sync_committee_messages{job=\"validator-client-job\"} / validator_performance_expected_sync_committee_messages{job=\"validator-client-job\"}",
     "legendFormat": "Included Signatures"
    },
    {
     "expr": "validator_performance_produced_sync_committee_messages{job=\"validator-client-job\"} / validator_performance_expected_sync_committee_messages{job=\"validator-client-job\"}",
     "legendFormat": "Produced Signatures"
    },
    {
     "expr": "validator_performance_correct_sync_committee_messages{job=\"validator-client-job\"} / validator_performance_produced_sync_committee_messages{job=\"validator-client-job\"}",
     "legendFormat": "Correct Signatures"
    }
   ]
  },
  {
   "title": "Validator Counts",
   "type": "stat",
   "description": "Counts of active, slashed and exited validators.",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_current_active_validators{job=\"consensus-client-job\"}",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "description": "Number of pending and existing validators over time. Pending validators are shown as positive values, while exiting validators are shown as negative values.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "validators" }
   ],
   "targets": [
    {
     "expr": "beacon_current_active_validators{job=\"consensus-client-job\"}",
     "legendFormat": "active validators"
    }
   ]
  },
  {
   "title": "Client Status",
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "The number of peers to which the beacon chain is connected",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "libp2p_peers{job=\"consensus-client-job\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Process Uptimes",
   "type": "stat",
   "description": "The length of time the beacon chain and validator processes have been running.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"consensus-client-job\"})/3600",
     "legendFormat": "beacon chain"
    },
    {
     "expr": "(time()-process_start_time_seconds{job=\"validator-client-job\"})/3600",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "Server",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Client Memory Usage",
   "type": "graph",
   "description": "Beacon chain and validator memory usage on the server.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"consensus-client-job\"}",
     "legendFormat": "beacon memory"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"validator-client-job\"}",
     "legendFormat": "validator memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Processor usage on the server",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"system\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"user\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"nice\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"iowait\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"steal\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"idle\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"irq\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"softirq\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"guest\",job=\"node-exporter-job\"}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "Network transmission (tx) and reception (rx) rates",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node-exporter-job\",device='enp1s0'}[5m])*8 or irate(node_network_transmit_bytes{job=\"node-exporter-job\",device='enp1s0'}[5m])*8 or irate(node_network_transmit_bytes_total{job=\"node-exporter-job\",device='eno1'}[5m])*8 or irate(node_network_transmit_bytes{job=\"node-exporter-job\",device='eno1'}[5m])*8",
     "legendFormat": "tx"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node-exporter-job\",device='enp1s0'}[5m])*8 or irate(node_network_receive_bytes{job=\"node-exporter-job\",device='enp1s0'}[5m])*8 or irate(node_network_receive_bytes_total{job=\"node-exporter-job\",device='eno1'}[5m])*8 or irate(node_network_receive_bytes{job=\"node-exporter-job\",device='eno1'}[5m])*8",
     "legendFormat": "rx"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job=\"node-exporter-job\"})-sum(node_filesystem_avail_bytes{job=\"node-exporter-job\"}))/sum(node_filesystem_size_bytes{job=\"node-exporter-job\"})",
     "legendFormat": "disk usage"
    }
   ]
  },
  {
   "title": "Server Memory Usage",
   "type": "graph",
   "description": "Memory usage on the server",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{job=\"node-exporter-job\"} - node_memory_MemFree_bytes{job=\"node-exporter-job\"} - node_memory_Buffers_bytes{job=\"node-exporter-job\"} - node_memory_Cached_bytes{job=\"node-exporter-job\"} - node_memory_SwapCached_bytes{job=\"node-exporter-job\"} - node_memory_Slab_bytes{job=\"node-exporter-job\"} - node_memory_PageTables_bytes{job=\"node-exporter-job\"} - node_memory_VmallocUsed_bytes{job=\"node-exporter-job\"} ) or ( node_memory_MemTotal{job=\"node-exporter-job\"} - node_memory_MemFree{job=\"node-exporter-job\"} - node_memory_Buffers{job=\"node-exporter-job\"} - node_memory_Cached{job=\"node-exporter-job\"} - node_memory_SwapCached{job=\"node-exporter-job\"} - node_memory_Slab{job=\"node-exporter-job\"} - node_memory_PageTables{job=\"node-exporter-job\"} - node_memory_VmallocUsed{job=\"node-exporter-job\"} )",
     "legendFormat": "apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter-job\"} or node_memory_Buffers{job=\"node-exporter-job\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter-job\"} or node_memory_Cached{job=\"node-exporter-job\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter-job\"} or node_memory_MemFree{job=\"node-exporter-job\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_Slab_bytes{job=\"node-exporter-job\"} or node_memory_Slab{job=\"node-exporter-job\"}",
     "legendFormat": "slab"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_coretemp_0\",job=\"node-exporter-job\",sensor=\"temp1\"}",
     "legendFormat": "cpu temp"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"google-ping-job\"}",
     "legendFormat": "google"
    },
    {
     "expr": "probe_duration_seconds{job=\"cloudflare-ping-job\"}",
     "legendFormat": "cloudflare"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Consensus Process Down",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"consensus-client-job\"}",
     "legendFormat": "beacon node"
    }
   ]
  },
  {
   "title": "Less than 2GB Free Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes{job=\"node-exporter-job\"} or node_memory_MemFree{job=\"node-exporter-job\"}) + (node_memory_Cached_bytes{job=\"node-exporter-job\"} or node_memory_Cached{job=\"node-exporter-job\"})"
    }
   ]
  },
  {
   "title": "Google Ping above 10ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"google-ping-job\"}"
    }
   ]
  },
  {
   "title": "CPU Usage above 40%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",job=\"node-exporter-job\"}[5m])) or sum(irate(node_cpu{mode=\"user\",job=\"node-exporter-job\"}[5m]))"
    }
   ]
  },
  {
   "title": "Consensus Process Restarted",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"consensus-client-job\"})/3600",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Validator Process Down",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"validator-client-job\"}",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "Validator Process Restarted",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"validator-client-job\"})/3600"
    }
   ]
  },
  {
   "title": "CPU Temperature above 85 °C",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_coretemp_0\",job=\"node-exporter-job\",sensor=\"temp1\"}"
    }
   ]
  },
  {
   "title": "Below 40 Peers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libp2p_peers{job=\"consensus-client-job\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "50 Slots Behind",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((beacon_clock_time_slot{job=\"consensus-client-job\"} / 32) - beacon_head_slot{job=\"consensus-client-job\"})",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "Disk Usage above 60%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job=\"node-exporter-job\"})-sum(node_filesystem_avail_bytes{job=\"node-exporter-job\"}))/sum(node_filesystem_size_bytes{job=\"node-exporter-job\"})"
    }
   ]
  },
  {
   "title": "Participation Rate below 80%",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(beacon_previous_live_validators{job=\"consensus-client-job\"} / beacon_previous_active_validators{job=\"consensus-client-job\"}) * 100"
    }
   ]
  }
 ]
}